version: '3'
services:
  app:
    build:
      context: .
    tty: true
    environment:
      - NODE_ENV=development
      - PORT=8080
    volumes:
      - ./:/usr/src
    command: sh -c "yarn start"
    ports:
      - "8080:8080"